name: firebase_analytics
description:
  Flutter plugin for Google Analytics for Firebase, an app measurement
  solution that provides insight on app usage and user engagement on Android and iOS.
homepage: https://firebase.google.com/docs/analytics
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_analytics/firebase_analytics
version: 10.8.9

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v2.27.0+1
      path: packages/firebase_analytics/firebase_analytics_platform_interface
  firebase_core:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v2.27.0+1
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v2.27.0+1
      path: packages/firebase_core/firebase_core_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.analytics
        pluginClass: FlutterFirebaseAnalyticsPlugin
      ios:
        pluginClass: FLTFirebaseAnalyticsPlugin
      macos:
        pluginClass: FLTFirebaseAnalyticsPlugin
