name: firebase_app_check
description: App Check works alongside other Firebase services to help protect your backend resources from abuse, such as billing fraud or phishing.
homepage: https://firebase.google.com/docs/app-check
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_check/firebase_app_check
version: 0.2.1+17

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_app_check_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v2.27.0+1
      path: packages/firebase_app_check/firebase_app_check_platform_interface
  firebase_core:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v2.27.0+1
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v2.27.0+1
      path: packages/firebase_core/firebase_core_platform_interface
  flutter:
    sdk: flutter

dev_dependencies:
  async: ^2.5.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.appcheck
        pluginClass: FlutterFirebaseAppCheckPlugin
      ios:
        pluginClass: FLTFirebaseAppCheckPlugin
      macos:
        pluginClass: FLTFirebaseAppCheckPlugin
