name: firebase_crashlytics
description:
  Flutter plugin for Firebase Crashlytics. It reports uncaught errors to the
  Firebase console.
version: 4.3.0
homepage: https://firebase.google.com/docs/crashlytics
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_crashlytics/firebase_crashlytics
topics:
  - firebase
  - crashlytics
  - errors
  - crashes

false_secrets:
  - example/**

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v3.10.0+1
      path: packages/firebase_core/firebase_core
  firebase_core_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v3.10.0+1
      path: packages/firebase_core/firebase_core_platform_interface
  firebase_crashlytics_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v3.10.0+1
      path: packages/firebase_crashlytics/firebase_crashlytics_platform_interface
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.crashlytics
        pluginClass: FlutterFirebaseCrashlyticsPlugin
      ios:
        pluginClass: FLTFirebaseCrashlyticsPlugin
      macos:
        pluginClass: FLTFirebaseCrashlyticsPlugin
