name: firebase_analytics_platform_interface
description: A common platform interface for the firebase_analytics plugin.
homepage: https://github.com/firebase/flutterfire/tree/main/packages/firebase_analytics/firebase_analytics_platform_interface
repository: https://github.com/firebase/flutterfire/tree/main/packages/firebase_analytics/firebase_analytics_platform_interface
version: 4.3.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v3.10.0+1
      path: packages/_flutterfire_internals
  firebase_core:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v3.10.0+1
      path: packages/firebase_core/firebase_core
  flutter:
    sdk: flutter
  meta: ^1.8.0
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface:
    git:
      url: https://github.com/guide-inc-org/guide-flutter_fire.git
      ref: kcfx/v3.10.0+1
      path: packages/firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
